"""Contains functionality associated with errors and exceptions."""

import re
import textwrap
import traceback

from abc import abstractmethod
from dataclasses import dataclass, field, InitVar, make_dataclass
from enum import Enum
from functools import cached_property, singledispatch
from io import StringIO
from pathlib import Path
from typing import Self

from dbrownell_ParserLib.region import Location, Region


# ----------------------------------------------------------------------
# |
# |  Public Types
# |
# ----------------------------------------------------------------------
@dataclass(frozen=True)
class Error:
    """Base class for all errors generated by this library."""

    # ----------------------------------------------------------------------
    message: str

    region_or_regions: InitVar[Region | list[Region]]
    regions: list[Region] = field(init=False)

    # ----------------------------------------------------------------------
    @classmethod
    def CreateAsException(cls, *args, **kwargs) -> ErrorException:
        """Create an `ErrorException` with an `Error` based on the provided arguments."""

        return ErrorException(cls(*args, **kwargs))

    # ----------------------------------------------------------------------
    def __post_init__(self, region_or_regions: Region | list[Region]) -> None:
        regions = [region_or_regions] if isinstance(region_or_regions, Region) else region_or_regions

        if not regions:
            msg = "At least one region must be provided"
            raise ValueError(msg)

        object.__setattr__(self, "regions", regions)

    # ----------------------------------------------------------------------
    def __str__(self) -> str:
        return self._string

    # ----------------------------------------------------------------------
    # ----------------------------------------------------------------------
    # ----------------------------------------------------------------------
    @cached_property
    def _string(self) -> str:
        if len(self.regions) == 1 and "\n" not in self.message:
            return f"{self.message} ({self.regions[0]})"

        return textwrap.dedent(
            """\
            {}

            {}
            """,
        ).format(self.message.rstrip(), "\n".join(f"    - {region}" for region in self.regions))


# ----------------------------------------------------------------------
@dataclass(frozen=True)
class PythonError(Error):
    """An `Error` based on a Python exception."""

    # ----------------------------------------------------------------------
    ex: Exception

    # ----------------------------------------------------------------------
    @classmethod
    def Create(
        cls,
        ex: Exception,
    ) -> Self:
        """Create a `PythonError` from a Python exception."""

        regions: list[Region] = []

        # I haven't been able to find a reliable way to get the exception's callstack so it is being
        # parsed manually here. There has got to be a better way to do this.
        sink = StringIO()

        traceback.print_exception(ex, file=sink)
        sink_str = sink.getvalue()

        regex = re.compile(r"^\s*File \"(?P<filename>.+?)\", line (?P<line>\d+),.+$", re.MULTILINE)

        for line in sink_str.splitlines():
            match = regex.match(line)
            if not match:
                continue

            line_number = int(match.group("line"))

            regions.append(
                Region(
                    Path(match.group("filename")),
                    Location(line_number, 1),
                    Location(line_number, 1),
                ),
            )

        regions.reverse()

        return cls(
            textwrap.dedent(
                """\
                Python Exception
                ----------------
                {}
                """,
            ).format(str(ex)),
            regions,
            ex,
        )


# ----------------------------------------------------------------------
class ErrorException(Exception):  # noqa: N818
    """Python exception that contains an `Error` object."""

    # ----------------------------------------------------------------------
    def __init__(self, error: Error) -> None:
        super().__init__(str(error))
        self.error = error


# ----------------------------------------------------------------------
# |
# |  Public Functions
# |
# ----------------------------------------------------------------------
class _CreatedError(Error):
    """Abstract base class for errors created via `CreateErrorType`."""

    # ----------------------------------------------------------------------
    @classmethod
    @abstractmethod
    def Create(cls, region_or_regions: Region | list[Region], *args, **kwargs) -> Self: ...


# ----------------------------------------------------------------------
def CreateErrorType(
    message_template: str,
    **error_attributes: type,
) -> type[_CreatedError]:
    """Create a new `Error` type with the provided message template and attributes.

    Example:
        MyError = CreateErrorType(
            "This is an error with attribute {attr1} and {attr2}",
            attr1=str,
            attr2=int,
        )

    """

    dynamic_fields_class = make_dataclass(
        "DynamicFields",
        error_attributes.items(),
        bases=(_CreatedError,),
        frozen=True,
    )

    # ----------------------------------------------------------------------
    @dataclass(frozen=True)
    class NewError(dynamic_fields_class):  # ty: ignore[unsupported-base]
        # ----------------------------------------------------------------------
        @classmethod
        def Create(
            cls,
            region_or_regions: Region | list[Region],
            *args,
            **kwargs,
        ) -> Self:
            """Create a new instance of this error type."""

            kvps = {k: _ArgToString(v) for k, v in zip(error_attributes.keys(), args, strict=False)}

            for k, v in kwargs.items():
                kvps[k] = _ArgToString(v)

            return cls(
                message_template.format(**kvps),  # ty: ignore[too-many-positional-arguments]
                region_or_regions,
                *args,
                **kwargs,
            )

        # ----------------------------------------------------------------------
        @classmethod
        def CreateAsException(cls, *args, **kwargs) -> ErrorException:
            return ErrorException(cls.Create(*args, **kwargs))

    # ----------------------------------------------------------------------

    return NewError


# ----------------------------------------------------------------------
# |
# |  Private Functions
# |
# ----------------------------------------------------------------------
@singledispatch
def _ArgToString(value: object) -> str:
    return str(value)


@_ArgToString.register
def _(value: str) -> str:
    return value


@_ArgToString.register
def _(value: Enum) -> str:
    return value.name


@_ArgToString.register
def _(value: list) -> str:
    return "[{}]".format(", ".join("'{}'".format(_ArgToString(v)) for v in value))
