"""Contains functionality associated with errors and exceptions."""

import re
import textwrap
import traceback

from dataclasses import dataclass, field, InitVar
from functools import cached_property
from io import StringIO
from pathlib import Path
from typing import Self

from dbrownell_ParserLib.region import Location, Region


# ----------------------------------------------------------------------
@dataclass(frozen=True)
class Error:
    """Base class for all errors generated by this library."""

    # ----------------------------------------------------------------------
    message: str

    region_or_regions: InitVar[Region | list[Region]]
    regions: list[Region] = field(init=False)

    # ----------------------------------------------------------------------
    def __post_init__(self, region_or_regions: Region | list[Region]) -> None:
        regions = [region_or_regions] if isinstance(region_or_regions, Region) else region_or_regions

        if not regions:
            msg = "At least one region must be provided"
            raise ValueError(msg)

        object.__setattr__(self, "regions", regions)

    # ----------------------------------------------------------------------
    def __str__(self) -> str:
        return self._string

    # ----------------------------------------------------------------------
    # ----------------------------------------------------------------------
    # ----------------------------------------------------------------------
    @cached_property
    def _string(self) -> str:
        if len(self.regions) == 1 and "\n" not in self.message:
            return f"{self.message} ({self.regions[0]})"

        return textwrap.dedent(
            """\
            {}

            {}
            """,
        ).format(self.message.rstrip(), "\n".join(f"    - {region}" for region in self.regions))


# ----------------------------------------------------------------------
@dataclass(frozen=True)
class PythonError(Error):
    """An `Error` based on a Python exception."""

    # ----------------------------------------------------------------------
    ex: Exception

    # ----------------------------------------------------------------------
    @classmethod
    def Create(
        cls,
        ex: Exception,
    ) -> Self:
        """Create a `PythonError` from a Python exception."""

        regions: list[Region] = []

        # I haven't been able to find a reliable way to get the exception's callstack so it is being
        # parsed manually here. There has got to be a better way to do this.
        sink = StringIO()

        traceback.print_exception(ex, file=sink)
        sink_str = sink.getvalue()

        regex = re.compile(r"^\s*File \"(?P<filename>.+?)\", line (?P<line>\d+),.+$", re.MULTILINE)

        for line in sink_str.splitlines():
            match = regex.match(line)
            if not match:
                continue

            line_number = int(match.group("line"))

            regions.append(
                Region(
                    Path(match.group("filename")),
                    Location(line_number, 1),
                    Location(line_number, 1),
                ),
            )

        regions.reverse()

        return cls(
            textwrap.dedent(
                """\
                Python Exception
                ----------------
                {}
                """,
            ).format(str(ex)),
            regions,
            ex,
        )
